In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Downloads/the-movies-dataset/movies_metadata.csv", low_memory=False)

In [3]:
df1=pd.DataFrame(df[['budget','genres','revenue','title','vote_average','vote_count']])

In [4]:
listOfGenres=['Animation', 'Adventure', 'Romance', 'Action', 'Comedy', 'Drama', 'Crime', 
              'History', 'Family', 'Fantasy', 'Science Fiction','Thriller', 
              'Music', 'Horror', 'Documentary', 'Mystery']

In [5]:
data=pd.DataFrame(df1['genres'])

In [6]:
for k in range(len(data)):
    col=data['genres'][k]
    genre_list=[]
    for genre in listOfGenres:
        if genre in col:
            genre_list.append(1)
        else:
            genre_list.append(0)
    data['genres'][k]= np.array(genre_list)

In [7]:
df1['genres']=data['genres']

In [8]:
df1['genres'][0]

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [9]:
lst=[]
numbers=range(len(df1['genres']))
for number in numbers:
    lst.append(df1['genres'][number])

In [10]:
lst[:5]

[array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

In [11]:
y=np.arange(16)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
from operator import itemgetter

In [13]:
df1['Animation']=list(map(itemgetter(0),lst))
df1['Adventure']=list(map(itemgetter(1),lst))
df1['Romance']=list(map(itemgetter(2),lst))
df1['Action']=list(map(itemgetter(3),lst))
df1['Comedy']=list(map(itemgetter(4),lst))
df1['Drama']=list(map(itemgetter(5),lst))
df1['Crime']=list(map(itemgetter(6),lst))
df1['History']=list(map(itemgetter(7),lst))
df1['Family']=list(map(itemgetter(8),lst))
df1['Fantasy']=list(map(itemgetter(9),lst))
df1['Science Fiction']=list(map(itemgetter(10),lst))
df1['Thriller']=list(map(itemgetter(11),lst))
df1['Music']=list(map(itemgetter(12),lst))
df1['Horror']=list(map(itemgetter(13),lst))
df1['Documentary']=list(map(itemgetter(14),lst))
df1['Mystery']=list(map(itemgetter(15),lst))

In [14]:
df1.head()

budget                                            genres      revenue  \
0  30000000  [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]  373554033.0   
1  65000000  [0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]  262797249.0   
2         0  [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]          0.0   
3  16000000  [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]   81452156.0   
4         0  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]   76578911.0   

                         title  vote_average  vote_count  Animation  \
0                    Toy Story           7.7      5415.0          1   
1                      Jumanji           6.9      2413.0          0   
2             Grumpier Old Men           6.5        92.0          0   
3            Waiting to Exhale           6.1        34.0          0   
4  Father of the Bride Part II           5.7       173.0          0   

   Adventure  Romance  Action   ...     Crime  History  Family  Fantasy  \
0          0        0       0   ...         0        0       1        0   
1          1        0       0   ...         0        0       1        1   
2          0        1       0   ...         0        0       0        0   
3          0        1       0   ...         0        0       0        0   
4          0        0       0   ...         0        0       0        0   

   Science Fiction  Thriller  Music  Horror  Documentary  Mystery  
0                0         0      0       0            0        0  
1                0         0      0       0            0        0  
2                0         0      0       0            0        0  
3                0         0      0       0            0        0  
4                0         0      0       0            0        0  

[5 rows x 22 columns]

In [15]:
df1['vote_count'].dtype

dtype('float64')

In [16]:
np.min(df1['vote_count'])

0.0

In [17]:
np.max(df1['vote_count'])

14075.0

In [18]:
df1['vote_count']=df1['vote_count']/14075

In [19]:
df1['vote_average']=df1['vote_average']/10

In [58]:
np.max(df1['vote_count'])

1.0

In [59]:
x=df1.iloc[:,5:22]
y=df1[['vote_average']]

In [60]:
w=pd.DataFrame(df1.iloc[:,4:22])
w.isnull().mean()*100

vote_average       0.013197
vote_count         0.013197
Animation          0.000000
Adventure          0.000000
Romance            0.000000
Action             0.000000
Comedy             0.000000
Drama              0.000000
Crime              0.000000
History            0.000000
Family             0.000000
Fantasy            0.000000
Science Fiction    0.000000
Thriller           0.000000
Music              0.000000
Horror             0.000000
Documentary        0.000000
Mystery            0.000000
dtype: float64

In [61]:
w.dropna(inplace=True)

In [62]:
w.isnull().mean()*100

vote_average       0.0
vote_count         0.0
Animation          0.0
Adventure          0.0
Romance            0.0
Action             0.0
Comedy             0.0
Drama              0.0
Crime              0.0
History            0.0
Family             0.0
Fantasy            0.0
Science Fiction    0.0
Thriller           0.0
Music              0.0
Horror             0.0
Documentary        0.0
Mystery            0.0
dtype: float64

In [63]:
w.head(10)

vote_average  vote_count  Animation  Adventure  Romance  Action  Comedy  \
0          0.77    0.384725          1          0        0       0       1   
1          0.69    0.171439          0          1        0       0       0   
2          0.65    0.006536          0          0        1       0       1   
3          0.61    0.002416          0          0        1       0       1   
4          0.57    0.012291          0          0        0       0       1   
5          0.77    0.133996          0          0        0       1       0   
6          0.62    0.010018          0          0        1       0       1   
7          0.54    0.003197          0          1        0       1       0   
8          0.55    0.012362          0          1        0       1       0   
9          0.66    0.084831          0          1        0       1       0   

   Drama  Crime  History  Family  Fantasy  Science Fiction  Thriller  Music  \
0      0      0        0       1        0                0         0      0   
1      0      0        0       1        1                0         0      0   
2      0      0        0       0        0                0         0      0   
3      1      0        0       0        0                0         0      0   
4      0      0        0       0        0                0         0      0   
5      1      1        0       0        0                0         1      0   
6      0      0        0       0        0                0         0      0   
7      1      0        0       1        0                0         0      0   
8      0      0        0       0        0                0         1      0   
9      0      0        0       0        0                0         1      0   

   Horror  Documentary  Mystery  
0       0            0        0  
1       0            0        0  
2       0            0        0  
3       0            0        0  
4       0            0        0  
5       0            0        0  
6       0            0        0  
7       0            0        0  
8       0            0        0  
9       0            0        0

In [64]:
x2=w.iloc[:,5:22]
y2=w[['vote_average']]

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2, test_size=0.2, random_state=0)

In [67]:
from sklearn.linear_model import LinearRegression

In [68]:
linear=LinearRegression()

In [69]:
linear.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [70]:
linear.predict(x_test)

array([[0.52626965],
       [0.54146955],
       [0.50674292],
       ...,
       [0.56881924],
       [0.65972544],
       [0.57177682]])

In [71]:
linear.score(x_test,y_test)

0.03289354385947607

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [76]:
from sklearn import preprocessing
from sklearn import utils

In [77]:
lab_enc = preprocessing.LabelEncoder()
y_training_scores_encoded = lab_enc.fit_transform(y_train)

/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [143]:
knn=KNeighborsClassifier(n_neighbors=100)

In [144]:
knn.fit(x_train, y_training_scores_encoded)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=100, p=2,
           weights='uniform')

In [145]:
knn_y_predict=knn.predict(x_test[:])

In [146]:
linear_y_predict=linear.predict(x_test)

In [147]:
e=pd.DataFrame(knn_y_predict / 100)

In [148]:
r=pd.DataFrame(y_test).reset_index()

In [149]:
e['actual y value']=r['vote_average']

In [150]:
e['linear y predicted value']=linear_y_predict

In [152]:
e.head(30)

0  actual y value  linear y predicted value
0   0.55            0.56                  0.526270
1   0.00            0.50                  0.541470
2   0.00            0.70                  0.506743
3   0.00            0.00                  0.571777
4   0.52            0.64                  0.585037
5   0.57            0.67                  0.578470
6   0.00            0.46                  0.541470
7   0.54            0.66                  0.614841
8   0.53            0.61                  0.605323
9   0.55            0.60                  0.532271
10  0.42            0.50                  0.570596
11  0.62            0.55                  0.626324
12  0.00            0.65                  0.506743
13  0.00            0.60                  0.571777
14  0.43            0.58                  0.566997
15  0.52            0.60                  0.514616
16  0.42            1.00                  0.570596
17  0.00            0.80                  0.592778
18  0.42            0.56                  0.570596
19  0.00            0.00                  0.506743
20  0.00            0.79                  0.571777
21  0.00            0.41                  0.541470
22  0.00            1.00                  0.571777
23  0.31            0.00                  0.541966
24  0.00            0.80                  0.506743
25  0.00            0.70                  0.506743
26  0.00            0.59                  0.539335
27  0.42            0.50                  0.595315
28  0.00            0.55                  0.541470
29  0.53            0.69                  0.605323

In [159]:
#both models are terrible at predicting the 'vote average'... (even if I use different k values)
#I think the choices for x features (popularity and genres) were not good. When looking at the 
#corr table below, all of x features do have very low corr score with vote_average
#features that I haven't used: runtime, revenue, budget (runtime and revenue also have low corr with vote_average)

In [160]:
df1.corr()

revenue  vote_average  vote_count  Animation  Adventure  \
revenue          1.000000      0.083868    0.812022   0.077683   0.206535   
vote_average     0.083868      1.000000    0.123607   0.071970   0.010180   
vote_count       0.812022      0.123607    1.000000   0.053357   0.176510   
Animation        0.077683      0.071970    0.053357   1.000000   0.139137   
Adventure        0.206535      0.010180    0.176510   0.139137   1.000000   
Romance         -0.001914      0.039976   -0.011913  -0.065834  -0.046915   
Action           0.123843     -0.007287    0.125088   0.015865   0.287349   
Comedy           0.014420      0.032392   -0.001034  -0.001445  -0.032496   
Drama           -0.045612      0.133768   -0.024401  -0.142151  -0.085576   
Crime            0.017678      0.043747    0.043542  -0.058156  -0.025422   
History         -0.001522      0.049619   -0.000918  -0.028716   0.030846   
Family           0.108904      0.017896    0.068560   0.336684   0.197079   
Fantasy          0.121536      0.020397    0.105005   0.150026   0.189407   
Science Fiction  0.087185     -0.038350    0.115931   0.069801   0.123293   
Thriller         0.040614     -0.000349    0.071465  -0.079176  -0.006459   
Music           -0.008434      0.025929   -0.016358  -0.000597  -0.038498   
Horror          -0.024247     -0.068212   -0.006238  -0.050189  -0.056089   
Documentary     -0.051852      0.032764   -0.060792  -0.054016  -0.074703   
Mystery          0.010718      0.025180    0.027261  -0.026932  -0.023577   

                  Romance    Action    Comedy     Drama     Crime   History  \
revenue         -0.001914  0.123843  0.014420 -0.045612  0.017678 -0.001522   
vote_average     0.039976 -0.007287  0.032392  0.133768  0.043747  0.049619   
vote_count      -0.011913  0.125088 -0.001034 -0.024401  0.043542 -0.000918   
Animation       -0.065834  0.015865 -0.001445 -0.142151 -0.058156 -0.028716   
Adventure       -0.046915  0.287349 -0.032496 -0.085576 -0.025422  0.030846   
Romance          1.000000 -0.094600  0.158882  0.185119 -0.066179 -0.006846   
Action          -0.094600  1.000000 -0.079886 -0.077519  0.158490  0.016708   
Comedy           0.158882 -0.079886  1.000000 -0.164278 -0.061699 -0.091910   
Drama            0.185119 -0.077519 -0.164278  1.000000  0.091464  0.115829   
Crime           -0.066179  0.158490 -0.061699  0.091464  1.000000 -0.031513   
History         -0.006846  0.016708 -0.091910  0.115829 -0.031513  1.000000   
Family          -0.035289 -0.032339  0.078610 -0.074673 -0.070777 -0.035247   
Fantasy         -0.004686  0.047021  0.013322 -0.070068 -0.062587 -0.034858   
Science Fiction -0.066997  0.158466 -0.063566 -0.131090 -0.063307 -0.045716   
Thriller        -0.104969  0.211295 -0.203772  0.003417  0.260105 -0.048912   
Music            0.070702 -0.066075  0.028611 -0.020006 -0.045834 -0.014623   
Horror          -0.117895 -0.039474 -0.114430 -0.183144 -0.048643 -0.053571   
Documentary     -0.122137 -0.118970 -0.169704 -0.242693 -0.085102  0.028147   
Mystery         -0.046859 -0.030575 -0.089288  0.015122  0.154603 -0.031414   

                   Family   Fantasy  Science Fiction  Thriller     Music  \
revenue          0.108904  0.121536         0.087185  0.040614 -0.008434   
vote_average     0.017896  0.020397        -0.038350 -0.000349  0.025929   
vote_count       0.068560  0.105005         0.115931  0.071465 -0.016358   
Animation        0.336684  0.150026         0.069801 -0.079176 -0.000597   
Adventure        0.197079  0.189407         0.123293 -0.006459 -0.038498   
Romance         -0.035289 -0.004686        -0.066997 -0.104969  0.070702   
Action          -0.032339  0.047021         0.158466  0.211295 -0.066075   
Comedy           0.078610  0.013322        -0.063566 -0.203772  0.028611   
Drama           -0.074673 -0.070068        -0.131090  0.003417 -0.020006   
Crime           -0.070777 -0.062587        -0.063307  0.260105 -0.045834   
History         -0.035247 -0.034858        -0.045716 -0.0489

In [161]:
df.head(10)

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
5  False                                                NaN  60000000   
6  False                                                NaN  58000000   
7  False                                                NaN         0   
8  False                                                NaN  35000000   
9  False  {'id': 645, 'name': 'James Bond Collection', '...  58000000   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   
5  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   
6  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
7  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
8  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
9  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...   

                                       homepage     id    imdb_id  \
0          http://toystory.disney.com/toy-story    862  tt0114709   
1                                           NaN   8844  tt0113497   
2                                           NaN  15602  tt0113228   
3                                           NaN  31357  tt0114885   
4                                           NaN  11862  tt0113041   
5                                           NaN    949  tt0113277   
6                                           NaN  11860  tt0114319   
7                                           NaN  45325  tt0112302   
8                                           NaN   9091  tt0114576   
9  http://www.mgm.com/view/movie/757/Goldeneye/    710  tt0113189   

  original_language               original_title  \
0                en                    Toy Story   
1                en                      Jumanji   
2                en             Grumpier Old Men   
3                en            Waiting to Exhale   
4                en  Father of the Bride Part II   
5                en                         Heat   
6                en                      Sabrina   
7                en                 Tom and Huck   
8                en                 Sudden Death   
9                en                    GoldenEye   

                                            overview    ...     release_date  \
0  Led by Woody, Andy's toys live happily in his ...    ...       1995-10-30   
1  When siblings Judy and Peter discover an encha...    ...       1995-12-15   
2  A family wedding reignites the ancient feud be...    ...       1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...    ...       1995-12-22   
4  Just when George Banks has recovered from his ...    ...       1995-02-10   
5  Obsessive master thief, Neil McCauley leads a ...    ...       1995-12-15   
6  An ugly duckling having undergone a remarkable...    ...       1995-12-15   
7  A mischievous young boy, Tom Sawyer, witnesses...    ...       1995-12-22   
8  International action superstar Jean Claude Van...    ...       1995-12-22   
9  James Bond must unmask the mysterious head of ...    ...       1995-11-16   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name'

In [162]:
df.corr()

revenue   runtime  vote_average  vote_count
revenue       1.000000  0.103917      0.083868    0.812022
runtime       0.103917  1.000000      0.158146    0.113539
vote_average  0.083868  0.158146      1.000000    0.123607
vote_count    0.812022  0.113539      0.123607    1.000000